// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8LltIXXBy2JcM_wfaqV_BwFlF5zyfGcs',
    appId: '1:944146882511:web:c1d76c60301c44cad8bcba',
    messagingSenderId: '944146882511',
    projectId: 'ozgurkal-712ee',
    authDomain: 'ozgurkal-712ee.firebaseapp.com',
    storageBucket: 'ozgurkal-712ee.firebasestorage.app',
    measurementId: 'G-14BM4WKPK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNM8J1dGDXujIukenGxaCxbG9ZFKZlEo0',
    appId: '1:944146882511:android:5fcb8a4add559b9ad8bcba',
    messagingSenderId: '944146882511',
    projectId: 'ozgurkal-712ee',
    storageBucket: 'ozgurkal-712ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYtwuRIOd3Ymip6pD0W1DCEPbMhvfHLc',
    appId: '1:944146882511:ios:b6d27316fd9e2eefd8bcba',
    messagingSenderId: '944146882511',
    projectId: 'ozgurkal-712ee',
    storageBucket: 'ozgurkal-712ee.firebasestorage.app',
    iosBundleId: 'com.example.ozgurkal1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALYtwuRIOd3Ymip6pD0W1DCEPbMhvfHLc',
    appId: '1:944146882511:ios:b6d27316fd9e2eefd8bcba',
    messagingSenderId: '944146882511',
    projectId: 'ozgurkal-712ee',
    storageBucket: 'ozgurkal-712ee.firebasestorage.app',
    iosBundleId: 'com.example.ozgurkal1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8LltIXXBy2JcM_wfaqV_BwFlF5zyfGcs',
    appId: '1:944146882511:web:094ecfe8eb1c22bcd8bcba',
    messagingSenderId: '944146882511',
    projectId: 'ozgurkal-712ee',
    authDomain: 'ozgurkal-712ee.firebaseapp.com',
    storageBucket: 'ozgurkal-712ee.firebasestorage.app',
    measurementId: 'G-GXH3YL1QFZ',
  );
}
